config/routes.rb
Rails.application.routes.draw do
  root to: 'seas#index'
  devise_for :users
  resources :seas, only: [:new,:create] 
  resources :homes, only:[:index,:show,:edit,:update,:destroy] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' }, { id: 3, name: '青森県' }, { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' }, { id: 7, name: '山形県' },
    { id: 8, name: '福島県' }, { id: 9, name: '茨城県' }, { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' }, { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' }, { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' }, { id: 18, name: '石川県' }, { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' }, { id: 21, name: '長野県' }, { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' }, { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' }, { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' }, { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' }, { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' }, { id: 36, name: '山口県' }, { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' }, { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' }, { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' }, { id: 45, name: '大分県' }, { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :seas
  
end

app/models/car.rb
class Car < ActiveHash::Base

  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'アリ' },
    { id: 3, name: '多数アリ' },
    { id: 4, name: 'ナシ' }
  ]
  include ActiveHash::Associations
  has_many :seas

end

app/models/sea.rb
class Sea < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :car
  belongs_to_active_hash :shower
  belongs_to_active_hash :area
  belongs_to :user
  has_one_attached :image

  validates :image, :seaname, :explanation, :address,    presence: true

  validates :area_id, :car_id, :shower_id,    numericality: {other_than: 1}
end

app/models/shower.rb
class Shower < ActiveHash::Base
  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: '有'},
    { id: 3, name: '無'}
  ]
  include ActiveHash::Associations
  has_many :seas

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :seas
         validates :name, presence: true
         PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
         validates_format_of :password, with: PASSWORD_REGEX, message: 'Password Include both letters and numbers'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_sea, only: [:show, :edit, :update, :destroy]
  def index
    @seas = Sea.all
  end

  def show
  end

  def destroy
    @sea.destroy if user_signed_in? && current_user.id == @sea.user_id
    redirect_to root_path
  end

  def edit
      unless @sea.user_id == current_user.id
      redirect_to action: :index 
      end
  end

  def update
    if @sea.update(sea_params)
      redirect_to homes_path
    else
      render :edit
    end
  end



  private

  def sea_params
      params.require(:sea).permit(:seaname, :address, :explanation, :car_id, :shower_id, :area_id, :image).merge(user_id: current_user.id)
  end

  def set_sea
    @sea = Sea.find(params[:id])
  end

end

app/controllers/seas_controller.rb
class SeasController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def index
    @seas = Sea.all
  end

  def new
    @sea = Sea.new
  end

  def create
    @sea = Sea.new(sea_params)
    if @sea.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def sea_params
    params.require(:sea).permit(:seaname, :address, :explanation, :car_id, :shower_id, :area_id, :image).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/seas_helper.rb
module SeasHelper
end

app/views/homes/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('Botanical Spring Time Header.jpg' , size: '350x100'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">海の情報を入力</h2>
    <%= form_with(model: @sea, url:home_path, method: :patch,local: true) do |f| %>

    <%#= render 'shared/error_messages', model: f.object %>
    
    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        おすすめ写真！！
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        海の名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :seaname, class:"items-text", id:"item-name", placeholder:"(例)片瀬東浜海水浴場", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          海の情報
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"items-text", id:"item-info", placeholder:"海の特徴(海が綺麗で、砂浜もビーチ感があり夏にはぴったりの海水浴場です。近辺にはサーフィンスクール、SUPなどサマースポーツが楽しめます！ぜひ一度お越しください)" ,rows:"7" ,maxlength:"1000" %>
      </div>
       <div class = "addresu">
        <div class = "weight-bold-text">
         場所   
         <span class ="indispensable">必須</span><%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
         </div>
          <%= f.text_area :address, class:"items-text", id:"item-name", placeholder:"詳細", maxlength:"40" %>
        </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">周辺詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          駐車場
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:car_id, Car.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          シャワー室完備の有無
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shower_id, Shower.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する", class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

app/views/homes/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
   <div class="container">
       <a class="navbar-brand js-scroll-trigger" href="/">Sea Discovery</a>
   </div>
</nav>

<div class='item-contents'>
      <h2 class='title'>Seas</h2>
        <ul class='item-lists'>
          <%if @seas %>
          <% @seas.each do |sea| %>
            <li class='list'>
            <%= link_to home_path(sea.id) do %>
              <div class='item-img-content'>
              <%= image_tag sea.image, class: "item-img" if sea.image.attached? %>
              </div>
                <div class='item-info'>
                  <h3 class='item-name'>
                  <%= sea.seaname %>
                  </h3>
                    <div class='item-price'>
                    <span><%= sea.area.name %><br><%= sea.address %></span>
                    </div>
                </div>
                  <% end %>
                 <% end %>
                <% end %>
             </li>
          </ul>
          <div class="search-form">
    <h2 class= htitle>GoogleMapで見つけよう！</h2>
    
      <input id="address" class='input-box' placeholder='キーワードから探す' >
      <button class="search-button" onclick="codeAddress()">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </div>
</div>

 <%= render "shared/footer" %>

app/views/homes/show.html.erb
<header class="top-page-header>">
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
   <div class="container">
       <a class="navbar-brand js-scroll-trigger" href="/">Sea Discovery</a>
          <div class="dis">
    <% if user_signed_in? && current_user.id == @sea.user_id %>
    <%= link_to '編集', edit_home_path(@sea.id), method: :get, class: "item-red-btn" %>
    <%= link_to '削除', home_path(@sea.id), method: :delete, class:'item-destroy' %>
    <% end %>
    </div>
   </div>
</nav>
</header>


<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @sea.seaname %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @sea.image, class:"item-box-img" %>
    </div>
    <div class="item-price-box">
      <span class="item-explnation">
        <%= @sea.area.name %>
      </span>
      <span class="item-postage">
        <%= @sea.address %>
      </span>
    </div>

    <div class="item-explain-box">
      <span><%= @sea.explanation %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= @sea.user.name %></td>
        </tr>
        <tr>
          <th class="detail-item">駐車場</th>
          <td class="detail-value"><%= @sea.car.name %></td>
        </tr>
        <tr>
          <th class="detail-item">シャワー完備</th>
          <td class="detail-value"><%= @sea.shower.name %></td>
        </tr>
      </tbody>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Sea Discovery</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
  <script src="http://maps.google.com/maps/api/js?key=AIzaSyAC5KQ5JsJEdpjWrliG6wdNDURtTILf8iI&callback=initMap" async defer></script>
  <style>
html { height: 100% }
body { height: 100% }
#map { height: 100%; width: 100%}
</style>
</head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/seas/index.html.erb
  <%= render "shared/header" %>

  <header class="masthead">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase text-white font-weight-bold">Sea Discovery</h1>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 font-weight-light mb-5">Sea Discoveryとは海好きな人たちが普段よく行く海を投稿し海の素晴らしさ、楽しさを共感してもらうアプリです。海の情報も掲載しみんながいきたいと思える海にしていこう！ </p>
                        <%= link_to 'Saes POST', new_sea_path, class: "btn btn-primary btn-xl js-scroll-trigger" %>
                    </div>
                </div>
            </div>
        </header>
 <%= render "shared/main" %>
  <%= render "shared/bottom" %>

app/views/seas/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('Botanical Spring Time Header.jpg' , size: '350x100'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">海の情報を入力</h2>
    <%= form_with model:@sea, url:seas_path, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
    
    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        おすすめ写真！！
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        海の名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :seaname, class:"items-text", id:"item-name", placeholder:"(例)片瀬東浜海水浴場", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          海の情報
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"items-text", id:"item-info", placeholder:"海の特徴(海が綺麗で、砂浜もビーチ感があり夏にはぴったりの海水浴場です。近辺にはサーフィンスクール、SUPなどサマースポーツが楽しめます！ぜひ一度お越しください)" ,rows:"7" ,maxlength:"1000" %>
      </div>
       <div class = "addresu">
        <div class = "weight-bold-text">
         場所   
         <span class ="indispensable">必須</span><%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
         </div>
          <%= f.text_area :address, class:"items-text", id:"item-name", placeholder:"詳細", maxlength:"40" %>
        </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">周辺詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          駐車場
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:car_id, Car.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          シャワー室完備の有無
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shower_id, Shower.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

app/views/shared/_bottom.html.erb
        <!-- Call to action-->
        <section class="page-section text-white">
            <div class="container text-center">
                <h2 class="mb-4">Enjoy the splendor of the sea</h2>
                <%= link_to 'Sea Discovery', homes_path,class:"btn btn-light btn-xl" %>
            </div>
        </section>
        <!-- Contact-->

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div id="map"></div>

<style>
#map {
  height: 600px;
  width: 1600px;
}
</style>

<script>
// let 再定義不可、再代入可能
let map
//initMapという関数名で処理かいし
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 33.60639, lng:130.41806},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 33.60639, lng:130.41806},
    map: map
  });
}
let geocoder

  //検索フォームのボタンが押された時に実行される
function codeAddress(){
  //検索フォームの入力内容を取得
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    //該当する検索結果がヒットした時に、地図の中心を検索結果の緯度経度に更新する
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      //検索結果が何もなかった場合に表示
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}
</script>

app/views/shared/_header.html.erb
     <header>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">Sea Discovery</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        <li class="nav-item"><%= link_to '投稿一覧', homes_path, class: "nav-link js-scroll-trigger" %></li>
                        <% if user_signed_in?%>
                        <li class="nav-item"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link js-scroll-trigger" %></li>
                        <% else %>
                        <li class="nav-item"><%= link_to 'ログイン', new_user_session_path, class: "nav-link js-scroll-trigger" %></li>
                        <li class="nav-item"><%= link_to '新規登録', new_user_registration_path, class: "nav-link js-scroll-trigger" %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
      </header>

app/views/shared/_main.html.erb
<div class='select-reason-contents'>
    <h2 class='title'>
      旅行に出掛けたら各地の海が確認できる!
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "animal-1868046_1920.jpg", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>海</span>
          好きが集まる
        </h3>
        <p class='reason-list-description'>
          地元のおすすめスポットをみんなに拡散しよう！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "man-5462849_1920.jpg", class:"list-picts" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>マリンスポーツ</span>
          が楽しめる
        </h3>
        <p class='reason-list-description'>
          その海にしかないレジャーを楽しもう！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "japan-989881_1920.jpg", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>周辺情報</span>
          がわかる!
        </h3>
        <p class='reason-list-description'>
          駐車場やシャワー室の情報がわかる!
        </p>
      </li>
    </ul>
  </div>